
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LexerParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EQEQ = 11;
  public static final int ABSTRACT = 2;
  public static final int INTEGER = 6;
  public static final int PUBLIC = 3;
  public static final int LITERAL = 7;
  public static final int BOOLEAN = 14;
  public static final int STRING_LITERAL = 8;
  public static final int PLUS = 12;
  public static final int EQ = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PRIVATE = 4;
  public static final int IDENTIFIER = 5;
  public static final int BREAK = 13;
  public static final int INTEGER_LITERAL = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABSTRACT",
  "PUBLIC",
  "PRIVATE",
  "IDENTIFIER",
  "INTEGER",
  "LITERAL",
  "STRING_LITERAL",
  "INTEGER_LITERAL",
  "EQ",
  "EQEQ",
  "PLUS",
  "BREAK",
  "BOOLEAN"
  };
}

