
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package syntaxis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BELSNICKEL = 12;
  public static final int FUNCTION = 49;
  public static final int TOTIN = 6;
  public static final int HADA = 39;
  public static final int PERSONA = 19;
  public static final int DOS_PUNTOS = 48;
  public static final int DUENDE = 40;
  public static final int CIERRECUENTO = 30;
  public static final int KNECHT_RUPRECHT = 10;
  public static final int RUDOLPH = 2;
  public static final int ENTREGA = 46;
  public static final int CIERRAREGALO = 34;
  public static final int ZWARTE_PIET = 13;
  public static final int ABREEMPAQUE = 31;
  public static final int CIERRAEMPAQUE = 32;
  public static final int SNOWBALL_ALABASTRO = 14;
  public static final int FIN_REGALO = 35;
  public static final int NARRA = 36;
  public static final int L_PAPA_NOEL = 28;
  public static final int MAIN = 50;
  public static final int HACE = 42;
  public static final int ENVUELVE = 41;
  public static final int KRAMPUS = 11;
  public static final int SANTA_CLAUS = 21;
  public static final int PAPA_NOEL = 20;
  public static final int NINO_JESUS = 23;
  public static final int SAN_NICOLAS = 22;
  public static final int GRINCH = 8;
  public static final int EOF = 0;
  public static final int CORTA = 45;
  public static final int MELCHOR = 16;
  public static final int REVISA = 43;
  public static final int error = 1;
  public static final int L_COLACHO = 26;
  public static final int COMA = 47;
  public static final int BALTASAR = 18;
  public static final int GASPAR = 17;
  public static final int ABRECUENTO = 29;
  public static final int PEPPER_MINSTIX = 15;
  public static final int ESCUCHA = 37;
  public static final int ABREREGALO = 33;
  public static final int DASHER = 3;
  public static final int ENVIA = 44;
  public static final int COLACHO = 24;
  public static final int COMET = 4;
  public static final int SANTA = 25;
  public static final int ELFO = 38;
  public static final int LOCAL = 51;
  public static final int VIXEN = 5;
  public static final int QUIEN = 9;
  public static final int L_SAN_NICOLAS = 27;
  public static final int RENILLO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RUDOLPH",
  "DASHER",
  "COMET",
  "VIXEN",
  "TOTIN",
  "RENILLO",
  "GRINCH",
  "QUIEN",
  "KNECHT_RUPRECHT",
  "KRAMPUS",
  "BELSNICKEL",
  "ZWARTE_PIET",
  "SNOWBALL_ALABASTRO",
  "PEPPER_MINSTIX",
  "MELCHOR",
  "GASPAR",
  "BALTASAR",
  "PERSONA",
  "PAPA_NOEL",
  "SANTA_CLAUS",
  "SAN_NICOLAS",
  "NINO_JESUS",
  "COLACHO",
  "SANTA",
  "L_COLACHO",
  "L_SAN_NICOLAS",
  "L_PAPA_NOEL",
  "ABRECUENTO",
  "CIERRECUENTO",
  "ABREEMPAQUE",
  "CIERRAEMPAQUE",
  "ABREREGALO",
  "CIERRAREGALO",
  "FIN_REGALO",
  "NARRA",
  "ESCUCHA",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "ENTREGA",
  "COMA",
  "DOS_PUNTOS",
  "FUNCTION",
  "MAIN",
  "LOCAL"
  };
}

